# -*- coding: utf-8 -*-
"""Lesson 1 - Number Variables and Types_20072025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10T31smMsi9iXY_7M82FPD94dIS84F7XN
"""



"""ipynb - internet python notebook

1.1 python datatype
classification of information
integer > number without decimals
float > numbers with decimals
string > text

1.2 basic python commands

# print() command
# name of command ()


"""

# print() show something on the screen

# i want to show ten
print(10)

# type() shows type of data we have

print(type(6.7))

"""1.3 Variables

variables are like containers to store data types

"""

mangoes = 10
#reusability
print(mangoes)
print(mangoes +2)
print(mangoes/5)

"""Rules to write variables
- no space
- don't start with numbers (1number - NO, number1 - YES)
- don't use "-"

Good practice
- snake_case = number_1
- camelCase = numberOne
"""